
```{r}
selected_columns <- c("Primary_Genre", "Size_MB", "Average_User_Rating", "Released_Year", "Free")

df <- df[selected_columns]
df$Free <- as.factor(df$Free)
levels(df$Free) <- c(0, 1)

# na_counts <- colSums(is.na(df))
# print(na_counts)
str(df)
```

### Logistic Regression
<p>
Why we are choosing Logistic Regression (I think - since the nature of the target variable is binomial in nature)
</p>

```{r}
logistic_model_2 <- glm(Free ~ .,data = df, family = binomial)
# summary(logistic_model_2)
```

## Confusion Matrix for Logistic Regression
```{r}
predictions_2 <- factor(ifelse(predict(logistic_model_2, type = "response") > 0.5, 1, 0), levels = levels(df$Free))
actual_values_2 <- factor(df$Free, levels = levels(df$Free))

conf_matrix_2 <- confusionMatrix(predictions_2, actual_values_2)
print(conf_matrix_2)
```
<p>
From the above model metrics we can see that, although the model's accuracy is over 90% and the specificity being over 99%
</p>
```{r}
logistic_model <- glm(Free ~ ., data = merged_df, family = binomial)
summary(logistic_model)
```

```{r}
predictions <- factor(ifelse(predict(logistic_model, type = "response") > 0.5, 1, 0), levels = levels(merged_df$Free))
actual_values <- factor(merged_df$Free, levels = levels(merged_df$Free))

conf_matrix <- confusionMatrix(predictions, actual_values)
print(conf_matrix)
```
# Random Forest

```{r}
selected_columns_3 <- c("Size_MB", "Average_User_Rating", "Released_Year", "Free")
dff <- df[selected_columns_3]
colnames(dff)
nrow(dff)
```

```{r}
# Assuming df is your data frame with the dependent variable 'Free' and other predictor variables

# Install and load the randomForest package if not already installed
# install.packages("randomForest")
library(randomForest)

# Set a seed for reproducibility
set.seed(123)

library(doParallel)
cl <- makeCluster(detectCores())
registerDoParallel(cl)

rf_model <- randomForest(Free ~ ., data = merged_df, ntree = 500, mtry = sqrt(ncol(merged_df) - 1), ncores = detectCores())

```

```{r}
summary(rf_model)
```

```{r}
# Assuming 'your_test_data' is your testing dataset
# predictions_rf <- factor(ifelse(predict(rf_model, newdata = merged_df, type = "response") > 0.5, 1, 0), levels = levels(merged_df$Free))
predictions_rf <- predict(rf_model, newdata = merged_df, type = "response")
results_rf <- data.frame(Actual = merged_df$Free, Predicted = predictions_rf)
library(caret)

# Create a confusion matrix
confusion_matrix_rf <- confusionMatrix(table(results_rf$Predicted, results_rf$Actual))
print(confusion_matrix_rf)
```
